export enum DocumentFIleExtensionEnum {
  json = '../../assets/json.svg',
  js = '../../assets/javascript.svg',
  html = '../../assets/html.svg',
  css = '../../assets/css.svg',
  scss = '../../assets/sass.svg',
  map = '../../assets/css-map.svg',
  jpg = '../../assets/image.svg',
  jpeg = '../../assets/image.svg',
  png = '../../assets/image.svg',
  svg = '../../assets/image.svg',
  pdf = '../../assets/pdf.svg',
  txt = '../../assets/txt.svg',
  zip = '../../assets/zip.svg',
  php = '../../assets/php.svg',
  ico = '../../assets/favicon.svg',
  htaccess = '../../assets/credits.svg',
}
