export enum DocumentFIleExtensionEnum {
  json = 'https://projects.acdaling.nl/ftp_client/assets/json.svg',
  js = 'https://projects.acdaling.nl/ftp_client/assets/javascript.svg',
  html = 'https://projects.acdaling.nl/ftp_client/assets/html.svg',
  css = 'https://projects.acdaling.nl/ftp_client/assets/css.svg',
  scss = 'https://projects.acdaling.nl/ftp_client/assets/sass.svg',
  map = 'https://projects.acdaling.nl/ftp_client/assets/css-map.svg',
  jpg = 'https://projects.acdaling.nl/ftp_client/assets/image.svg',
  jpeg = 'https://projects.acdaling.nl/ftp_client/assets/image.svg',
  png = 'https://projects.acdaling.nl/ftp_client/assets/image.svg',
  svg = 'https://projects.acdaling.nl/ftp_client/assets/image.svg',
  pdf = 'https://projects.acdaling.nl/ftp_client/assets/pdf.svg',
  txt = 'https://projects.acdaling.nl/ftp_client/assets/txt.svg',
  zip = 'https://projects.acdaling.nl/ftp_client/assets/zip.svg',
  php = 'https://projects.acdaling.nl/ftp_client/assets/php.svg',
  ico = 'https://projects.acdaling.nl/ftp_client/assets/favicon.svg',
  htaccess = 'https://projects.acdaling.nl/ftp_client/assets/credits.svg',
}
